instance_name: cpcd_0
bus_type: UART
uart_device_file: {{ .device }}
uart_device_baud: {{ .baudrate }}
uart_hardflow: {{ .flow_control }}
bootloader_recovery_pins_enabled: false
trace_level: {{ .trace_level }}
trace_to_file: false
trace_to_syslog: false
rlimit_nofile: 2000
disable_encryption: true
# zigbeed (iid 1) and otbr-agent (iid 2) share the 15.4 endpoint
multicast_endpoints: [12]
